<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Unit Test Results: All Errors</title>
<link rel="stylesheet" type="text/css" title="Style" href="stylesheet.css">
</head>
<body onload="open('allclasses-frame.html','classListFrame')">
<h1>Unit Test Results.</h1>
<table width="100%">
<tr>
<td align="left"></td><td align="right">Designed for use with <a href="http://www.junit.org/">JUnit</a> and <a href="http://ant.apache.org/">Ant</a>.</td>
</tr>
</table>
<hr size="1">
<h2>All Errors</h2>
<table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
<tr valign="top">
<th>Class</th><th>Name</th><th>Status</th><th width="80%">Type</th><th nowrap>Time(s)</th>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testEliminarHotelF"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testEliminarHotelF">testEliminarHotelF</a></td><td>Error</td><td>org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Hotel#1]<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Hotel#1]<br>	at edu.uag.iidis.scec.persistencia.HotelDAO.buscarPorId(HotelDAO.java:52)<br>	at edu.uag.iidis.scec.pruebas.HotelDAOTest.testEliminarHotelF(HotelDAOTest.java:244)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Hotel#1]<br>	at org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:237)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:210)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.lockAndLoad(DefaultLoadEventListener.java:361)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:151)<br>	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)<br>	at org.hibernate.internal.SessionImpl.load(SessionImpl.java:920)<br>	at org.hibernate.internal.SessionImpl.load(SessionImpl.java:911)<br>	at edu.uag.iidis.scec.persistencia.HotelDAO.buscarPorId(HotelDAO.java:39)<br>
</code></td><td>0.019</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testActualizarHotelF"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testActualizarHotelF">testActualizarHotelF</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.HotelDAOTest.testActualizarHotelF(HotelDAOTest.java:123)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.056</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testEliminarHotelE"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testEliminarHotelE">testEliminarHotelE</a></td><td>Error</td><td>org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Hotel#1]<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Hotel#1]<br>	at edu.uag.iidis.scec.persistencia.HotelDAO.buscarPorId(HotelDAO.java:52)<br>	at edu.uag.iidis.scec.pruebas.HotelDAOTest.testEliminarHotelE(HotelDAOTest.java:222)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Hotel#1]<br>	at org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:237)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:210)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.lockAndLoad(DefaultLoadEventListener.java:361)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:151)<br>	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)<br>	at org.hibernate.internal.SessionImpl.load(SessionImpl.java:920)<br>	at org.hibernate.internal.SessionImpl.load(SessionImpl.java:911)<br>	at edu.uag.iidis.scec.persistencia.HotelDAO.buscarPorId(HotelDAO.java:39)<br>
</code></td><td>0.007</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testActualizarHotelE"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testActualizarHotelE">testActualizarHotelE</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.HotelDAOTest.testActualizarHotelE(HotelDAOTest.java:94)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.040</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testordenarHotelesPorE"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testordenarHotelesPorE">testordenarHotelesPorE</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.HotelDAO.ordenarHotelesPor(HotelDAO.java:88)<br>	at edu.uag.iidis.scec.pruebas.HotelDAOTest.testordenarHotelesPorE(HotelDAOTest.java:273)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:59)<br>	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1053)<br>	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1108)<br>	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)<br>	at edu.uag.iidis.scec.persistencia.HotelDAO.ordenarHotelesPor(HotelDAO.java:74)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.042</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testCrearHotelE"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testCrearHotelE">testCrearHotelE</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.HotelDAOTest.testCrearHotelE(HotelDAOTest.java:38)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.046</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testCrearHotelF"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testCrearHotelF">testCrearHotelF</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.HotelDAOTest.testCrearHotelF(HotelDAOTest.java:66)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.043</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testEliminarCriticaE"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testEliminarCriticaE">testEliminarCriticaE</a></td><td>Error</td><td>org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Critica#1]<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Critica#1]<br>	at edu.uag.iidis.scec.persistencia.CriticaDAO.buscarPorId(CriticaDAO.java:52)<br>	at edu.uag.iidis.scec.pruebas.CriticaDAOTest.testEliminarCriticaE(CriticaDAOTest.java:208)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Critica#1]<br>	at org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:237)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:210)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.lockAndLoad(DefaultLoadEventListener.java:361)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:151)<br>	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)<br>	at org.hibernate.internal.SessionImpl.load(SessionImpl.java:920)<br>	at org.hibernate.internal.SessionImpl.load(SessionImpl.java:911)<br>	at edu.uag.iidis.scec.persistencia.CriticaDAO.buscarPorId(CriticaDAO.java:39)<br>
</code></td><td>0.011</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testCrearCriticaF"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testCrearCriticaF">testCrearCriticaF</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.CriticaDAOTest.testCrearCriticaF(CriticaDAOTest.java:60)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.044</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testordenarCriticaesPorE"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testordenarCriticaesPorE">testordenarCriticaesPorE</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.CriticaDAO.ordenarCriticaesPor(CriticaDAO.java:88)<br>	at edu.uag.iidis.scec.pruebas.CriticaDAOTest.testordenarCriticaesPorE(CriticaDAOTest.java:255)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:59)<br>	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1053)<br>	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1108)<br>	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)<br>	at edu.uag.iidis.scec.persistencia.CriticaDAO.ordenarCriticaesPor(CriticaDAO.java:74)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.034</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testCrearCriticaE"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testCrearCriticaE">testCrearCriticaE</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.CriticaDAOTest.testCrearCriticaE(CriticaDAOTest.java:35)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.035</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testEliminarCriticaF"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testEliminarCriticaF">testEliminarCriticaF</a></td><td>Error</td><td>org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Critica#1]<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Critica#1]<br>	at edu.uag.iidis.scec.persistencia.CriticaDAO.buscarPorId(CriticaDAO.java:52)<br>	at edu.uag.iidis.scec.pruebas.CriticaDAOTest.testEliminarCriticaF(CriticaDAOTest.java:230)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.uag.iidis.scec.modelo.Critica#1]<br>	at org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:237)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:210)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.lockAndLoad(DefaultLoadEventListener.java:361)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:151)<br>	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)<br>	at org.hibernate.internal.SessionImpl.load(SessionImpl.java:920)<br>	at org.hibernate.internal.SessionImpl.load(SessionImpl.java:911)<br>	at edu.uag.iidis.scec.persistencia.CriticaDAO.buscarPorId(CriticaDAO.java:39)<br>
</code></td><td>0.006</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testActualizarCriticaE"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testActualizarCriticaE">testActualizarCriticaE</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.CriticaDAOTest.testActualizarCriticaE(CriticaDAOTest.java:84)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.064</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testActualizarCriticaF"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testActualizarCriticaF">testActualizarCriticaF</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.CriticaDAOTest.testActualizarCriticaF(CriticaDAOTest.java:109)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry '001' for key 'Nombre'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.037</td>
</tr>
</table>
</body>
</html>
